# Generated by Django 5.0.7 on 2024-08-20 09:31

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
